### PR TITLE
Feat: Coolant Support

### PR DESCRIPTION
**Pull request by bdistin**
This is my naive solution to adding coolant support to MOS/FPP. I am not sure how to resume coolant after parking (when resuming from pause), but the initial design here seems to work: 
plxXTTj 1

This is predicated on the idea of defining an air solenoid to digital pin 0 and a fluid solenoid to digital pin 1, and/or a pump to pin 2; in your RepRap firmware config. eg:

pins.sys
```
M950 P0 C"PD12"
M950 P1 C"PD13"
M950 P2 C"PD14"
```

### CODE REVIEW

**Comment by bdistin** [comment]
Everything is working as I expect it from my testing. I am not a free-cad user, nor a python dev, so I will leave that post-processor work up to you @benagricola

**Comment by bdistin** [comment]
Quirks (for documentation):

Seems to turn off slightly before cutting is done. (does not synchronously wait for move actions to complete) Not that big a deal, but may be surprising behaviour.

M226 (synchronous pause) will turn off coolants, but will not restore states upon resume. Now I added these manually to a file to pause for me to manually flip a part. I am not sure if there is a way to add these via post-processor, so this may be a non-issue.

**Comment by bdistin** [comment]
Solved in #90

**Comment by benagricola** [comment]
Thanks for the initial implementation @bdistin and for being the first outside contributor to MillenniumOS!

**Pull request closed without merging**
